### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by thatnzguy** [JPhilipp/AIConnectors#1]
Hi, I've dropped this folder into a Unity 2022.1.22f1 and get the following compile errors:

`Assets\AIConnectors-main\GlobalUse\Misc.cs(276,64): error CS0246: The type or namespace name 'Layers' could not be found (are you missing a using directive or an assembly reference?)
`

If I comment out the referenced methods (since these are not currently used) there are some more compile errors, variations of this:
`Assets\AIConnectors-main\ImageAI\DallE\ImageAIDallE.cs(32,21): error CS0029: Cannot implicitly convert type 'byte[]' to 'string'
`
And a few others. Are there other dependencies I should be including with this project?

Thanks!

**Comment by JPhilipp** [comment]
Thanks for the note! I'll try fix these soon and will let you know.

**Comment by JPhilipp** [comment]
It should be fixed now, please pull latest, thanks again!

https://github.com/JPhilipp/AIConnectors/commit/95f30429605f447b1a55d30a3e49d2376d075575

**Comment by thatnzguy** [comment]
Works great, thanks :)
